<template>
  <v-container>
      <form>
        <v-text-field
          v-model="email"
          :error-messages="errors"
          label="E-mail"
          required
        ></v-text-field>
        <v-text-field
          v-model="password"
          :error-messages="errors"
          label="Password"
          required
        ></v-text-field>
        <v-btn elevation="2" rounded to="/" class="mr-4">
          Cancel
        </v-btn>
        <v-btn
          elevation="2"
          rounded 
          type="submit"
          color="info" 
        >
          Se connecter
        </v-btn>
      </form>
  </v-container>
</template>