<template>
  <v-container>
      <form>
        <v-text-field
          v-model="name"
          :counter="10"
          :error-messages="errors"
          label="Name"
          required
        ></v-text-field>
        <v-text-field
          v-model="phoneNumber"
          :counter="7"
          :error-messages="errors"
          label="Phone Number"
          required
        ></v-text-field>
        <v-text-field
          v-model="email"
          :error-messages="errors"
          label="E-mail"
          required
        ></v-text-field>
        <v-btn
          elevation="2"
          rounded 
          class="mr-4"
          type="submit"
        >
          submit
        </v-btn>
        <v-btn elevation="2" rounded to="/" color="secondary">
          Cancel
        </v-btn>
      </form>
  </v-container>
</template>